import { NextPage } from 'next';
import Head from 'next/head';
import Modifications from '../../components/Modifications/Modifications';

const ModificationPage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
            <Modifications/>
		</>
	);
};

export default ModificationPage;
